# This file contains values from Cookiecutter

default_context:
  project_name: "explicit-content-api"
  project_description: "API for classifying explicit images"
  organization: "explicit-content-api"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "explicit_content_api"
  email: "rezashabrang.m@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
