version: "3.7"

services:
    explicit-detector:
        build:
            dockerfile: Dockerfile.dev
            context: .
        image: explicit-detector
        container_name: explicit-detector
        networks:
            - explicit-net
        environment:
            WEB_CONCURRENCY: ${WEB_CONCURRENCY}
            API_KEY: ${API_KEY}
            LOG_LEVEL: ${LOG_LEVEL}
        volumes:
            - .:/app/
            - /app/.venv
        ports:
            - "8000:80"

networks:
    explicit-net:
        name: explicit-net